# Generated by Django 5.2.13 on 2026-09-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="job_url",
            field=models.URLField(blank=True),
        ),
    ]
