# Generated by Django 5.2.13 on 2026-09-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0002_application_job_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="source",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
